apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - echo1.test.qill.in
    secretName: echo-tls
  rules:
  - host: echo1.test.qill.in
    http:
      paths:
      - backend:
          serviceName: echo1
          servicePort: 80